/*
 * This source file was generated by the Gradle 'init' task
 */
package robot;

import robot.Robot.heading;

public class App {

    public static void main(String[] args) {
        Robot r = new Robot(5, 5, 1, 2, heading.N);
        try {
            r.processCommands("RFRFFRFRF");
        } catch (Exception e) {
            System.out.println(e.getMessage());
            //return;
        }
        System.out.println(r.report());
    }
}
