/*
 * This source file was generated by the Gradle 'init' task
 */
package robot;

import org.junit.jupiter.api.Test;

import robot.Robot.heading;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    Robot r1 = new Robot(5, 5, 1, 2, heading.N);
    Robot r2 = new Robot(5, 5, 0, 0, heading.E);
    Robot r3 = new Robot(1, 1, 0, 0, heading.W);
        
    @Test void robotInitializedCorrectly() {
        String expectedR1 = "Grid:5,5 Pos:1,2 Heading:N";
        assertEquals(expectedR1, r1.toString());
        String expectedR2 = "Grid:5,5 Pos:0,0 Heading:E";
        assertEquals(expectedR2, r2.toString());
    }

    @Test void robotMovedCorrectly() throws Exception {
        r1.processCommands("RFRFFRFRF");
        assertEquals("Report: 1 3 N", r1.report());
        r2.processCommands("RFLFFLRF");
        assertEquals("Report: 3 1 E", r2.report());
    }    

    @Test void OutofBoundsException() throws Exception {
        assertThrows(java.lang.Exception.class, () -> {
            r3.processCommands("F"); 
        });
    }  
}
