/*
 * This source file was generated by the Gradle 'init' task
 */
package robot;

import org.junit.jupiter.api.Test;

import robot.Robot.heading;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
        
    @Test void robotInitializedCorrectly() throws Exception {
        Robot r1 = new Robot(5, 5, 1, 2, heading.N);
        Robot r2 = new Robot(5, 5, 0, 0, heading.E);
        String expectedR1 = "Grid:5,5 Pos:1,2 Heading:N";
        assertEquals(expectedR1, r1.toString());
        String expectedR2 = "Grid:5,5 Pos:0,0 Heading:E";
        assertEquals(expectedR2, r2.toString());
    }

    @Test void robotMovedCorrectly() throws Exception {
        Robot r0 = new Robot(5, 7, 3, 3, heading.N);
        Robot r1 = new Robot(5, 5, 1, 2, heading.N);
        Robot r2 = new Robot(5, 5, 0, 0, heading.E);
        r0.processCommands("LFFRFRFRFF");
        assertEquals("Report: 2 4 S", r0.report());
        r1.processCommands("RFRFFRFRF");
        assertEquals("Report: 1 3 N", r1.report());
        r2.processCommands("RFLFFLRF");
        assertEquals("Report: 3 1 E", r2.report());
    }    

    @Test void OutofBoundsException() throws Exception {
        Robot r3 = new Robot(1, 1, 0, 0, heading.W);
        assertThrows(java.lang.Exception.class, () -> {
            r3.processCommands("F"); 
        });
        assertThrows(java.lang.Exception.class, () -> {
            Robot r4 = new Robot(1, 1, -1, 0, heading.W);
        });
    }  

    @Test void robotIgnoresUnknownCommands() throws Exception {
        Robot r4 = new Robot(10, 10, 4, 5, heading.S);
        Robot r4c = (Robot) r4.clone();
        r4.processCommands("RLORLBLRORLTF");
        r4c.processCommands("RLRLLRRLF");
        assertEquals(r4.report(), r4c.report());
    }
}
